import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { Guest, TimelineEvent, Table, BudgetItem, ChecklistItem } from '../types'

// ============================================
// PDF EXPORTS
// ============================================

export function exportGuestListPDF(
  guests: Guest[],
  tables: Table[],
  coupleNames: string,
  weddingDate: string
) {
  const doc = new jsPDF()

  // Header
  doc.setFontSize(24)
  doc.setTextColor(201, 127, 102) // Primary color
  doc.text('Guest List', 105, 20, { align: 'center' })

  doc.setFontSize(12)
  doc.setTextColor(100)
  doc.text(coupleNames, 105, 30, { align: 'center' })
  if (weddingDate) {
    doc.text(weddingDate, 105, 37, { align: 'center' })
  }

  // Summary stats
  const attending = guests.filter(g => g.rsvpStatus === 'attending').length
  const declined = guests.filter(g => g.rsvpStatus === 'declined').length
  const pending = guests.filter(g => g.rsvpStatus === 'pending').length

  doc.setFontSize(10)
  doc.setTextColor(60)
  doc.text(`Total Invited: ${guests.length}  |  Attending: ${attending}  |  Declined: ${declined}  |  Pending: ${pending}`, 105, 47, { align: 'center' })

  // Guest table
  const tableData = guests.map(guest => {
    const table = tables.find(t => t.guests.includes(guest.id))
    return [
      `${guest.firstName} ${guest.lastName}`,
      guest.rsvpStatus.charAt(0).toUpperCase() + guest.rsvpStatus.slice(1),
      guest.mealChoice || '-',
      guest.dietaryRestrictions?.join(', ') || '-',
      table?.name || 'Unassigned',
      guest.plusOne ? (guest.plusOneName || 'Yes') : 'No'
    ]
  })

  autoTable(doc, {
    startY: 55,
    head: [['Name', 'RSVP', 'Meal', 'Dietary', 'Table', 'Plus One']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [201, 127, 102],
      textColor: 255,
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [253, 248, 246]
    },
    styles: {
      fontSize: 9,
      cellPadding: 3
    }
  })

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(
      `Generated by Beginnings and Endings Wedding Planner - Page ${i} of ${pageCount}`,
      105,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    )
  }

  doc.save(`guest-list-${new Date().toISOString().split('T')[0]}.pdf`)
}

export function exportTimelinePDF(
  events: TimelineEvent[],
  coupleNames: string,
  weddingDate: string
) {
  const doc = new jsPDF()

  // Header
  doc.setFontSize(24)
  doc.setTextColor(201, 127, 102)
  doc.text('Wedding Day Timeline', 105, 20, { align: 'center' })

  doc.setFontSize(12)
  doc.setTextColor(100)
  doc.text(coupleNames, 105, 30, { align: 'center' })
  if (weddingDate) {
    doc.text(weddingDate, 105, 37, { align: 'center' })
  }

  // Sort events by start time
  const sortedEvents = [...events].sort((a, b) => a.startTime.localeCompare(b.startTime))

  // Timeline entries
  let yPos = 55
  const lineHeight = 25

  sortedEvents.forEach((event, index) => {
    if (yPos > 260) {
      doc.addPage()
      yPos = 20
    }

    // Time
    doc.setFontSize(11)
    doc.setTextColor(201, 127, 102)
    doc.text(`${event.startTime} - ${event.endTime}`, 20, yPos)

    // Title
    doc.setFontSize(12)
    doc.setTextColor(40)
    doc.text(event.title, 70, yPos)

    // Location
    if (event.location) {
      doc.setFontSize(9)
      doc.setTextColor(100)
      doc.text(event.location, 70, yPos + 6)
    }

    // Description
    if (event.description) {
      doc.setFontSize(8)
      doc.setTextColor(120)
      const descLines = doc.splitTextToSize(event.description, 120)
      doc.text(descLines.slice(0, 2), 70, yPos + (event.location ? 12 : 6))
    }

    // Divider line
    if (index < sortedEvents.length - 1) {
      doc.setDrawColor(230)
      doc.line(20, yPos + lineHeight - 5, 190, yPos + lineHeight - 5)
    }

    yPos += lineHeight
  })

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(
      `Generated by Beginnings and Endings Wedding Planner - Page ${i} of ${pageCount}`,
      105,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    )
  }

  doc.save(`wedding-timeline-${new Date().toISOString().split('T')[0]}.pdf`)
}

export function exportSeatingChartPDF(
  tables: Table[],
  guests: Guest[],
  coupleNames: string,
  weddingDate: string
) {
  const doc = new jsPDF()

  // Header
  doc.setFontSize(24)
  doc.setTextColor(201, 127, 102)
  doc.text('Seating Chart', 105, 20, { align: 'center' })

  doc.setFontSize(12)
  doc.setTextColor(100)
  doc.text(coupleNames, 105, 30, { align: 'center' })
  if (weddingDate) {
    doc.text(weddingDate, 105, 37, { align: 'center' })
  }

  // Summary
  const totalSeats = tables.reduce((sum, t) => sum + t.capacity, 0)
  const seatedGuests = tables.reduce((sum, t) => sum + t.guests.length, 0)

  doc.setFontSize(10)
  doc.setTextColor(60)
  doc.text(`${tables.length} Tables  |  ${totalSeats} Total Seats  |  ${seatedGuests} Guests Seated`, 105, 47, { align: 'center' })

  // Tables
  let yPos = 60

  tables.forEach((table) => {
    if (yPos > 250) {
      doc.addPage()
      yPos = 20
    }

    // Table header
    doc.setFillColor(253, 248, 246)
    doc.rect(15, yPos - 5, 180, 10, 'F')

    doc.setFontSize(11)
    doc.setTextColor(201, 127, 102)
    doc.text(`${table.name}`, 20, yPos + 2)

    doc.setFontSize(9)
    doc.setTextColor(100)
    doc.text(`${table.shape} | Capacity: ${table.capacity} | Seated: ${table.guests.length}`, 190, yPos + 2, { align: 'right' })

    yPos += 12

    // Guests at this table
    const tableGuests = table.guests
      .map(gId => guests.find(g => g.id === gId))
      .filter(Boolean) as Guest[]

    if (tableGuests.length === 0) {
      doc.setFontSize(9)
      doc.setTextColor(150)
      doc.text('No guests assigned', 25, yPos)
      yPos += 8
    } else {
      tableGuests.forEach((guest, idx) => {
        doc.setFontSize(9)
        doc.setTextColor(60)
        const guestInfo = `${guest.firstName} ${guest.lastName}`
        const mealInfo = guest.mealChoice ? ` (${guest.mealChoice})` : ''
        doc.text(`${idx + 1}. ${guestInfo}${mealInfo}`, 25, yPos)
        yPos += 6
      })
    }

    yPos += 8
  })

  // Unseated guests
  const unseatedGuests = guests.filter(g => !g.tableAssignment)
  if (unseatedGuests.length > 0) {
    if (yPos > 230) {
      doc.addPage()
      yPos = 20
    }

    doc.setFontSize(11)
    doc.setTextColor(200, 100, 100)
    doc.text(`Unseated Guests (${unseatedGuests.length})`, 20, yPos)
    yPos += 8

    unseatedGuests.forEach((guest, idx) => {
      if (yPos > 280) {
        doc.addPage()
        yPos = 20
      }
      doc.setFontSize(9)
      doc.setTextColor(100)
      doc.text(`${idx + 1}. ${guest.firstName} ${guest.lastName}`, 25, yPos)
      yPos += 5
    })
  }

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(
      `Generated by Beginnings and Endings Wedding Planner - Page ${i} of ${pageCount}`,
      105,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    )
  }

  doc.save(`seating-chart-${new Date().toISOString().split('T')[0]}.pdf`)
}

export function exportBudgetPDF(
  budgetItems: BudgetItem[],
  totalBudget: number,
  coupleNames: string,
  weddingDate: string
) {
  const doc = new jsPDF()

  // Header
  doc.setFontSize(24)
  doc.setTextColor(201, 127, 102)
  doc.text('Wedding Budget', 105, 20, { align: 'center' })

  doc.setFontSize(12)
  doc.setTextColor(100)
  doc.text(coupleNames, 105, 30, { align: 'center' })
  if (weddingDate) {
    doc.text(weddingDate, 105, 37, { align: 'center' })
  }

  // Summary
  const totalEstimated = budgetItems.reduce((sum, item) => sum + item.estimatedCost, 0)
  const totalActual = budgetItems.reduce((sum, item) => sum + item.actualCost, 0)
  const totalPaid = budgetItems.reduce((sum, item) => sum + item.paid, 0)

  doc.setFontSize(10)
  doc.setTextColor(60)
  doc.text(
    `Budget: $${totalBudget.toLocaleString()}  |  Estimated: $${totalEstimated.toLocaleString()}  |  Actual: $${totalActual.toLocaleString()}  |  Paid: $${totalPaid.toLocaleString()}`,
    105, 47, { align: 'center' }
  )

  // Budget table
  const tableData = budgetItems
    .filter(item => item.estimatedCost > 0 || item.actualCost > 0)
    .map(item => [
      item.category,
      item.vendor,
      `$${item.estimatedCost.toLocaleString()}`,
      `$${item.actualCost.toLocaleString()}`,
      `$${item.paid.toLocaleString()}`,
      `$${(item.actualCost - item.paid).toLocaleString()}`
    ])

  autoTable(doc, {
    startY: 55,
    head: [['Category', 'Vendor', 'Estimated', 'Actual', 'Paid', 'Balance']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [201, 127, 102],
      textColor: 255,
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [253, 248, 246]
    },
    styles: {
      fontSize: 9,
      cellPadding: 3
    },
    foot: [[
      '', 'TOTAL',
      `$${totalEstimated.toLocaleString()}`,
      `$${totalActual.toLocaleString()}`,
      `$${totalPaid.toLocaleString()}`,
      `$${(totalActual - totalPaid).toLocaleString()}`
    ]],
    footStyles: {
      fillColor: [240, 240, 240],
      textColor: 60,
      fontStyle: 'bold'
    }
  })

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(
      `Generated by Beginnings and Endings Wedding Planner - Page ${i} of ${pageCount}`,
      105,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    )
  }

  doc.save(`wedding-budget-${new Date().toISOString().split('T')[0]}.pdf`)
}

export function exportChecklistPDF(
  checklist: ChecklistItem[],
  coupleNames: string,
  weddingDate: string
) {
  const doc = new jsPDF()

  // Header
  doc.setFontSize(24)
  doc.setTextColor(201, 127, 102)
  doc.text('Wedding Checklist', 105, 20, { align: 'center' })

  doc.setFontSize(12)
  doc.setTextColor(100)
  doc.text(coupleNames, 105, 30, { align: 'center' })
  if (weddingDate) {
    doc.text(weddingDate, 105, 37, { align: 'center' })
  }

  // Summary
  const completed = checklist.filter(t => t.completed).length
  const progress = checklist.length > 0 ? Math.round((completed / checklist.length) * 100) : 0

  doc.setFontSize(10)
  doc.setTextColor(60)
  doc.text(`${completed} of ${checklist.length} tasks completed (${progress}%)`, 105, 47, { align: 'center' })

  // Checklist table
  const tableData = checklist.map(item => [
    item.completed ? '✓' : '○',
    item.title,
    item.category,
    item.priority,
    item.dueDate || '-',
    item.notes || '-'
  ])

  autoTable(doc, {
    startY: 55,
    head: [['Done', 'Task', 'Category', 'Priority', 'Due Date', 'Notes']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [201, 127, 102],
      textColor: 255,
      fontStyle: 'bold'
    },
    alternateRowStyles: {
      fillColor: [253, 248, 246]
    },
    styles: {
      fontSize: 9,
      cellPadding: 3
    },
    columnStyles: {
      0: { halign: 'center', cellWidth: 12 },
      3: { halign: 'center' }
    }
  })

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(
      `Generated by Beginnings and Endings Wedding Planner - Page ${i} of ${pageCount}`,
      105,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    )
  }

  doc.save(`wedding-checklist-${new Date().toISOString().split('T')[0]}.pdf`)
}

// ============================================
// ICS CALENDAR EXPORT
// ============================================

export function exportTimelineICS(
  events: TimelineEvent[],
  weddingDate: string,
  coupleNames: string
): void {
  if (!weddingDate) {
    alert('Please set your wedding date first')
    return
  }

  const formatICSDate = (date: string, time: string): string => {
    const [year, month, day] = date.split('-')
    const [hours, minutes] = time.split(':')
    return `${year}${month}${day}T${hours}${minutes}00`
  }

  const escapeICS = (text: string): string => {
    return text
      .replace(/\\/g, '\\\\')
      .replace(/;/g, '\\;')
      .replace(/,/g, '\\,')
      .replace(/\n/g, '\\n')
  }

  const icsEvents = events.map((event) => {
    const uid = `${event.id}@beginnings-and-endings-wedding`
    const dtStart = formatICSDate(weddingDate, event.startTime)
    const dtEnd = formatICSDate(weddingDate, event.endTime)
    const summary = escapeICS(event.title)
    const location = event.location ? escapeICS(event.location) : ''
    const description = event.description ? escapeICS(event.description) : ''

    return [
      'BEGIN:VEVENT',
      `UID:${uid}`,
      `DTSTAMP:${formatICSDate(new Date().toISOString().split('T')[0], '00:00')}`,
      `DTSTART:${dtStart}`,
      `DTEND:${dtEnd}`,
      `SUMMARY:${summary}`,
      location ? `LOCATION:${location}` : '',
      description ? `DESCRIPTION:${description}` : '',
      'END:VEVENT'
    ].filter(Boolean).join('\r\n')
  }).join('\r\n')

  const icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Beginnings and Endings Wedding Planner//EN',
    `X-WR-CALNAME:${escapeICS(coupleNames)} Wedding`,
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    icsEvents,
    'END:VCALENDAR'
  ].join('\r\n')

  // Download the file
  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `wedding-timeline-${weddingDate}.ics`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

// ============================================
// SHAREABLE LINK GENERATION
// ============================================

export function generateShareableLink(
  data: {
    guests?: Guest[]
    timeline?: TimelineEvent[]
    weddingDetails?: {
      coupleNames: string
      weddingDate: string
      venue: string
    }
  },
  type: 'rsvp' | 'timeline' | 'info'
): string {
  // Encode essential data for shareable link
  const shareData = {
    type,
    ...data,
    generated: new Date().toISOString()
  }

  // Create a base64 encoded string (in production, you'd use a backend with proper URLs)
  const encoded = btoa(JSON.stringify(shareData))

  // For now, return a hash-based URL that works client-side
  return `${window.location.origin}/share#${encoded}`
}

export function parseShareableLink(hash: string): any {
  try {
    const encoded = hash.replace('#', '')
    return JSON.parse(atob(encoded))
  } catch {
    return null
  }
}
